n = input('Digite Algo: ')
print('O tipo primitivo é: ', type(n))
print('é alphanumérico? ',n.isalnum())
print('é um número? ',n.isnumeric())
print('é parte do alfabeto? ',n.isalpha())
print('é decimal? ',n.isdecimal())
print('é um espaço? ',n.isspace())
print('é Maiúsculo? ',n.isupper())
print('é Minúsculo? ',n.islower())